package com.nailcase.model.enums;

public enum NotificationType {
    RESERVATION_REQUEST,
    RESERVATION_CANCEL,
    RESERVATION_APPROVE,
    RESERVATION_REJECT,
    RESERVATION_COMPLETE,
    NEW_CHAT_MESSAGE_TO_MEMBER,
    NEW_CHAT_MESSAGE_TO_SHOP
}
