x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
#  environment:
#    MINIO_ROOT_USER: minioadmin
#    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    restart: always
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: newtips-postgresql

  backend:
    image: newtips/nail-case-server
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - redis
      - postgresql
    environment:
      # SPRING APPLICATION
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: newtips-server
      # SPRING JPA
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_OPEN-IN-VIEW: false
      # DB: PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/newtips-postgresql
      SPRING_DATASOURCE_DRIVER-CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgresql
      SPRING_DATASOURCE_PASSWORD: postgresql
      # SPRING REDIS
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # S3 - MINIO
      CLOUD_AWS_CREDENTIALS_ACCESS-KEY: minioadmin
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: minioadmin
      CLOUD_AWS_REGION_STATIC: ap-northeast-2
      CLOUD_AWS_S3_ENDPOINT: http://nginx:9000
      CLOUD_AWS_S3_BUCKET: newtips-bucket-azxwettoqoqaaz
      # SPRING OAUTH2 CLIENT
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT-ID: # 채워주세요
      # H2
      SPRING_H2_CONSOLE_ENABLED: true


volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
