services:
  minio:
    image: bitnami/minio
    volumes:
      - minio-data:/bitnami/minio/data
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    restart: always
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: newtips-postgresql

  backend:
    image: newtips/nail-case-server
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - minio
      - redis
      - postgresql
    environment:
      # SPRING APPLICATION
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: prod
      SPRING_APPLICATION_NAME: newtips-server
      # SPRING JPA
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_OPEN-IN-VIEW: false
      # DB: PostgreSQL
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/newtips-postgresql
      SPRING_DATASOURCE_DRIVER-CLASS_NAME: org.postgresql.Driver
      SPRING_DATASOURCE_USERNAME: postgresql
      SPRING_DATASOURCE_PASSWORD: postgresql
      # SPRING REDIS
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # S3 - MINIO
      CLOUD_AWS_CREDENTIALS_ACCESS-KEY: minioadmin
      CLOUD_AWS_CREDENTIALS_SECRET_KEY: minioadmin
      CLOUD_AWS_REGION_STATIC: ap-northeast-2
      CLOUD_AWS_S3_ENDPOINT: http://minio:9000
      CLOUD_AWS_S3_BUCKET: newtips-bucket-azxwettoqoqaaz
      # SPRING OAUTH2 CLIENT
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KAKAO_CLIENT-ID: # 채워주세요
      # H2
      SPRING_H2_CONSOLE_ENABLED: true
      # JWT
      JWT_ACCESS_EXPIRATION: 923372036854775807
      JWT_REFRESH_EXPIRATION: 923372036854775807

      SPRING_JPA_SHOW-SQL: true
      LOGGING_LEVEL_ORG_HIBERNATE_ORM_JDBC_BIND: trace

volumes:
  minio-data:
