x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
#  environment:
#    MINIO_ROOT_USER: minioadmin
#    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgresql:
    image: postgres
    restart: always
    volumes:
      - ./volume/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: newtips-postgresql

  backend:
    image: "newtips/nail-case-server"
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - redis
      - postgresql
    environment:
      SERVER_PORT: 8080
      SPRING_APPLICATION_NAME: newtips-server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      cloud_aws_credentials_accessKey: minioadmin
      cloud_aws_credentials_secretKey: minioadmin
      cloud_aws_region_static: ap-northeast-2
      cloud_aws_s3_endpoint: "http://nginx:9000"
      cloud_aws_s3_bucket: newtips
      spring_datasource_url: jdbc:postgresql://postgresql:5432/newtips-postgresql
      spring_datasource_driverClassName: org.postgresql.Driver
      spring_datasource_username: postgresql
      spring_datasource_password: postgresql
      spring_jpa_hibernate_ddl-auto: update
      spring_jpa_open-in-view: false
#      logging_level_org_springframework: DEBUG

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
