name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - gh-pages-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build the project
      run: ./gradlew build

    - name: Start application
      run: |
        nohup ./gradlew bootRun &
        sleep 30

    - name: Generate Swagger UI static files
      run: |
        chmod +x generate-swagger-ui.sh
        ./generate-swagger-ui.sh

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./swagger-ui
