name: Deploy Swagger UI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build the project
        run: ./gradlew build -x test -Dspring.profiles.active=dev # 테스트 생략(다른 빌드 파일에서 테스트 진행)
        #run: ./gradlew build -x test -Dspring.profiles.active=prod # 실제 디비 반영 이후 주석 해제

      - name: Start application
        run: |
          CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${{ secrets.AWS_BACKEND_ACCESS_KEY }} \
          CLOUD_AWS_CREDENTIALS_SECRET_KEY=${{ secrets.AWS_BACKEND_SECRET_KEY }} \
          CLOUD_AWS_S3_ENDPOINT=https://s3.ap-northeast-2.amazonaws.com \
          JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
          KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
          KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }} \
          KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI }} \
          nohup ./gradlew bootRun &
          sleep 30

      - name: Generate Swagger UI static files
        run: |
          chmod +x generate-swagger-ui.sh
          ./generate-swagger-ui.sh

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./swagger-ui
          publish_branch: gh-pages
